server:
  port: 9527
spring:
  application:
    name: zuul-gateway-9527
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    #当前数据库类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com  #主机映射名称
    prefer-ip-address: true  #主机ip信息提示

info:
  app.name: com.qyn.cloud
  author: qiaoyn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  routes:
    mydept.serviceId: cloud-dept   #真实地址
    mydept.path: /mydept/**    #映射地址
  ignored-services: "*"  #忽略原地址
  prefix:  /qyn  #统一公共前缀